version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      TZ: Asia/Almaty 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # Save DB changes
      # - postgres_data:/var/lib/postgresql/data
      
      - ./build/scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
